server:
  port: 8880


spring:
  redis:
    host: 192.168.60.131
    port: 6379
    password: 123321
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: 100ms
        min-idle: 0
